create table dbt.stg_network(\
SiteName varchar(255),\
Room_Suite varchar(255),\
Address varchar(255),\
Town_City varchar(255),\
CountyFIPS varchar(255),\
CountyName varchar(255),\
State varchar(255),\
ZipCode varchar(255),\
Latitude varchar(255),\
Longitude varchar(255),\
Areacode varchar(255),\
Phonenumber varchar(255),\
DesignatedService varchar(255),\
NPI varchar(255),\
LicenseNumber_FacilityOperatingCertificate varchar(255),\
PFI varchar(255),\
MedicaidProviderIdentificationNumber varchar(255),\
CommercialProviderIndicator varchar(255),\
MedicaidProviderIndicator varchar(255),\
CHPIndicator varchar(255),\
HARPIndicator varchar(255),\
MedicaidAdvantageIndicator varchar(255),\
PartialCAPSIndicator varchar(255),\
MAPIndicator varchar(255),\
PACEIndicator varchar(255),\
FIDAIndicator varchar(255),\
FIDAIDDIndicator varchar(255),\
HIVSNPIndicator varchar(255),\
SIP_PLIndicator varchar(255),\
EP_Indicator_BasicHealthProgramIndicator varchar(255),\
AdultVision_Dental_BasicHealthProgramAdultIndicator varchar(255),\
CommercialNon_MCOMedicalIndicator1 varchar(255),\
CommercialNon_MCOMedicalIndicator2 varchar(255),\
CommercialNon_MCOMedicalIndicator3 varchar(255),\
CommercialNon_MCOMedicalIndicator4 varchar(255),\
CommercialNon_MCOMedicalIndicator5 varchar(255),\
CommercialNon_MCOMedicalIndicator6 varchar(255),\
CommercialNon_MCOMedicalIndicator7 varchar(255),\
CommercialNon_MCOMedicalIndicator8 varchar(255),\
Service1 varchar(255),\
Service2 varchar(255),\
Service3 varchar(255),\
Service4 varchar(255),\
Service5 varchar(255),\
Service6 varchar(255),\
Service7 varchar(255),\
Service8 varchar(255),\
Service9 varchar(255),\
Service10 varchar(255),\
Service11 varchar(255),\
Service12 varchar(255),\
Service13 varchar(255),\
Service14 varchar(255),\
Service15 varchar(255),\
Service16 varchar(255),\
Service17 varchar(255),\
Service18 varchar(255),\
Service19 varchar(255),\
Service20 varchar(255),\
Service21 varchar(255),\
Service22 varchar(255),\
Service23 varchar(255),\
Service24 varchar(255),\
Service25 varchar(255),\
NYSoHMedicalNetworkIndicator1 varchar(255),\
NYSoHMedicalNetworkIndicator2 varchar(255),\
NYSoHMedicalNetworkIndicator3 varchar(255),\
NYSoHMedicalNetworkIndicator4 varchar(255),\
NYSoHMedicalNetworkIndicator5 varchar(255),\
NYSoHMedicalNetworkIndicator6 varchar(255),\
NYSoHMedicalNetworkIndicator7 varchar(255),\
NYSoHMedicalNetworkIndicator8 varchar(255),\
NYSoHMedicalNetworkIndicator9 varchar(255),\
ServicingCounty1 varchar(255),\
ServicingCounty2 varchar(255),\
ServicingCounty3 varchar(255),\
ServicingCounty4 varchar(255),\
ServicingCounty5 varchar(255),\
OASASProgramReportingUnitNumber varchar(255),\
OASASProviderNumber varchar(255),\
OMHID varchar(255),\
PlanName varchar(255),\
ProviderNetworkDataSystemIdentificationNumber varchar(255),\
Quarter_Year varchar(255)\
);\
\
COPY dbt.stg_network(\
SiteName,Room_Suite,Address,Town_City,CountyFIPS,CountyName,State,ZipCode,Latitude,Longitude,Areacode,Phonenumber,DesignatedService,NPI,LicenseNumber_FacilityOperatingCertificate,PFI,MedicaidProviderIdentificationNumber,CommercialProviderIndicator,MedicaidProviderIndicator,CHPIndicator,HARPIndicator,MedicaidAdvantageIndicator,PartialCAPSIndicator,MAPIndicator,PACEIndicator,FIDAIndicator,FIDAIDDIndicator,HIVSNPIndicator,SIP_PLIndicator,EP_Indicator_BasicHealthProgramIndicator,AdultVision_Dental_BasicHealthProgramAdultIndicator,CommercialNon_MCOMedicalIndicator1,CommercialNon_MCOMedicalIndicator2,CommercialNon_MCOMedicalIndicator3,CommercialNon_MCOMedicalIndicator4,CommercialNon_MCOMedicalIndicator5,CommercialNon_MCOMedicalIndicator6,CommercialNon_MCOMedicalIndicator7,CommercialNon_MCOMedicalIndicator8,Service1,Service2,Service3,Service4,Service5,Service6,Service7,Service8,Service9,Service10,Service11,Service12,Service13,Service14,Service15,Service16,Service17,Service18,Service19,Service20,Service21,Service22,Service23,Service24,Service25,NYSoHMedicalNetworkIndicator1,NYSoHMedicalNetworkIndicator2,NYSoHMedicalNetworkIndicator3,NYSoHMedicalNetworkIndicator4,NYSoHMedicalNetworkIndicator5,NYSoHMedicalNetworkIndicator6,NYSoHMedicalNetworkIndicator7,NYSoHMedicalNetworkIndicator8,NYSoHMedicalNetworkIndicator9,ServicingCounty1,ServicingCounty2,ServicingCounty3,ServicingCounty4,ServicingCounty5,OASASProgramReportingUnitNumber,OASASProviderNumber,OMHID,PlanName,ProviderNetworkDataSystemIdentificationNumber,Quarter_Year\
)\
FROM '/data/institutional-provider-network-data-2020-quarter-1-1.csv'\
DELIMITER ','\
CSV HEADER;
